version: '3'
# ---------------------------------------------------------
# ---------------------------------------------------------
services:
# ---------------------------------------------------------
  postgres_fastapi:
    image: postgres:latest
    volumes:
      - ./postgres_fastapi_data:/var/lib/postgresql/data
    networks:
      keycloak-network-backend:
        ipv4_address: 172.16.238.2
    environment:
      POSTGRES_DB: pgadmin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
# ---------------------------------------------------------
# ---------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    networks:
      keycloak-network-backend:
        ipv4_address: 172.16.238.3
    environment:
      PGADMIN_DEFAULT_EMAIL : admin@admin.com
      PGADMIN_DEFAULT_PASSWORD : admin
    depends_on:
      - postgres_fastapi
# ---------------------------------------------------------
# ---------------------------------------------------------
  fastapi:
    build:
      context: ./fastapi_data
      dockerfile: ./Dockerfile
    volumes:
      - ./fastapi_data:/fastapi_data
      -  /etc/localtime:/etc/localtime:ro
      - ./fastapi_data/ssh:/root/.ssh
      - ./docker-compose.yml:/fastapi_data/docker-compose.yml
      - ./certificates:/certificates/
    privileged: true
    networks:
      keycloak-network-backend:
        ipv4_address: 172.16.238.4
    depends_on:
      - postgres_fastapi
# ---------------------------------------------------------
  fastapi_testing:
    build:
      context: ./fastapi_testing_data
      dockerfile: ./Dockerfile
    volumes:
      - ./fastapi_data:/fastapi_data
      - ./fastapi_testing_data:/fastapi_testing_data
      -  /etc/localtime:/etc/localtime:ro
      - ./fastapi_data/ssh:/root/.ssh
      - ./docker-compose.yml:/fastapi_data/docker-compose.yml
    networks:
      keycloak-network-backend:
        ipv4_address: 172.16.238.5
    depends_on:
      - postgres_fastapi
    extra_hosts:
      - fastapi.fast.pr:172.16.238.4
# ---------------------------------------------------------
# ---------------------------------------------------------
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime:ro
      - ./certificates:/etc/nginx/ssl/
    networks:
      keycloak-network-backend:
        ipv4_address: 172.16.238.6
    depends_on:
      - postgres_fastapi
      - fastapi
      - fastapi_testing
    ports:
      - 80:80
      - 443:443
# ---------------------------------------------------------
# ---------------------------------------------------------
networks:
  keycloak-network-backend:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
